### ISSUE TITLE
xml.etree.ElementTree.ParseError: XML or text declaration not at start of entity: line 2, column 0

### ISSUE THREAD

**Issue by ziggy90127** [not-a-feature/wd_fw_update#13]
Hi,

I have a WDS100T2B0C-00PXH0 (SN550 1TB) with firmware version 211070WD.  
```
nvme list
Node                  Generic               SN                   Model                                    Namespace Usage                      Format           FW Rev  
--------------------- --------------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme3n1          /dev/ng3n1            XXXXXXXXXXXX         WDC WDS100T2B0C-00PXH0                   1           1.00  TB /   1.00  TB    512   B +  0 B   211070WD
```

There is a firmware update available according to https://wddashboarddownloads.wdc.com/wdDashboard/config/devices/lista_devices.xml:

```
<lista_device model="WDC WDS100T2B0C-00PXH0">
<url>
wdDashboard/firmware/WDC_WDS100T2B0C-00PXH0/211210WD/device_properties.xml
</url>
</lista_device>
```

I did a git clone, and got the following:

```
(venv) root@z490:~/wd_fw_update# wd_fw_update 
Western Digital SSD Firmware Update Tool

[?] Select the NVME drive you want to update: 
 > /dev/nvme3n1

Traceback (most recent call last):
  File "/root/wd_fw_update/venv/bin/wd_fw_update", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/root/wd_fw_update/venv/lib/python3.11/site-packages/wd_fw_update/main.py", line 656, in run
    main(sys.argv[1:])
  File "/root/wd_fw_update/venv/lib/python3.11/site-packages/wd_fw_update/main.py", line 646, in main
    wd_fw_update()
  File "/root/wd_fw_update/venv/lib/python3.11/site-packages/wd_fw_update/main.py", line 598, in wd_fw_update
    get_upgrade_url(drive=drive)
  File "/root/wd_fw_update/venv/lib/python3.11/site-packages/wd_fw_update/main.py", line 446, in get_upgrade_url
    root = ET.fromstring(response.content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1338, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: XML or text declaration not at start of entity: line 2, column 0
```

I have used this tool to update 2 SN770's with no problems.

```
uname -a
Linux z490 6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) x86_64 GNU/Linux
```

**Comment by ziggy90127** [comment]
Appears to be a blank line at the top of the WD xml file:
```
wget https://wddashboarddownloads.wdc.com/wdDashboard/firmware/WDC_WDS100T2B0C-00PXH0/211210WD/device_properties.xml

nl -ba device_properties.xml 
     1	
     2	<?xml version="1.0"?>
     3	<ffu version="1.0">
     4	    <model>WDC WDS100T2B0C-00PXH0</model>
     5	    <fwmode>mode3</fwmode>
     6	    <fwversion>211210WD</fwversion>
     7	    <fwfile>211210WD.fluf</fwfile>
     8	    <dependency model="WDC WDS100T2B0C-00PXH0">211070WD</dependency>
     9	</ffu>

xmllint --valid device_properties.xml 
device_properties.xml:2: parser error : XML declaration allowed only at the start of the document
<?xml version="1.0"?>
     ^
```

**Comment by ziggy90127** [comment]
This fix, as suggested by chatGPT, which may not be the right thing to do, works for my case:

```
~/wd_fw_update/src/wd_fw_update# diff main.py.orig main.py
423a424,439
> def remove_blank_first_line(content_bytes):
>     # Decode bytes into a string (assumes UTF-8, adjust if needed)
>     content_str = content_bytes.decode('utf-8')
>     
>     # Split content into lines
>     lines = content_str.splitlines(keepends=True)
>     
>     # Check if the first line is blank
>     if lines and lines[0].strip() == "":
>         lines = lines[1:]  # Remove the first line if it's blank
>     
>     # Join the lines back and encode into bytes
>     cleaned_content = "".join(lines).encode('utf-8')
>     return cleaned_content
> 
> 
446c462,464
<     root = ET.fromstring(response.content)
---
>     content = remove_blank_first_line(response.content)
> 
>     root = ET.fromstring(content)
```

**Comment by not-a-feature** [comment]
You correctly identified the problem. It is a malformed xml file.
I'll implement a fix soon

**Comment by ziggy90127** [comment]
Thank you!
