### ISSUE TITLE
Can't find firmware for "WD PC SN740 SDDPTQD-1T00"

### ISSUE THREAD

**Issue by shelvacu** [not-a-feature/wd_fw_update#9]
Running NixOS on a Framework 16

```
$ wd_fw_update -vv
[[2024-06-28 13:46:13]] DEBUG:wd_fw_update.main:Namespace(loglevel=10)
[[2024-06-28 13:46:13]] INFO:wd_fw_update.main:Starting firmware update process.
Western Digital SSD Firmware Update Tool

[[2024-06-28 13:46:13]] DEBUG:wd_fw_update.main:Getting device list.
[[2024-06-28 13:46:13]] DEBUG:wd_fw_update.main:Asking for device: ['/dev/nvme0n1', '/dev/nvme1n1']

[?] Select the NVME drive you want to update: 
   /dev/nvme0n1
 > /dev/nvme1n1

[[2024-06-28 13:46:21]] DEBUG:wd_fw_update.main:Getting device properties.
[[2024-06-28 13:46:21]] INFO:wd_fw_update.main:Model name: WD PC SN740 SDDPTQD-1T00
[[2024-06-28 13:46:21]] DEBUG:wd_fw_update.main:Getting firmware url.
[[2024-06-28 13:46:21]] DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): wddashboarddownloads.wdc.com:443
[[2024-06-28 13:46:21]] DEBUG:urllib3.connectionpool:https://wddashboarddownloads.wdc.com:443 "GET /wdDashboard/config/devices/lista_devices.xml HTTP/11" 200 45945
Traceback (most recent call last):
  File "/tmp/tmp.B5xaB9c0ui/bin/wd_fw_update", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/tmp/tmp.B5xaB9c0ui/lib/python3.11/site-packages/wd_fw_update/main.py", line 555, in run
    main(sys.argv[1:])
  File "/tmp/tmp.B5xaB9c0ui/lib/python3.11/site-packages/wd_fw_update/main.py", line 545, in main
    wd_fw_update()
  File "/tmp/tmp.B5xaB9c0ui/lib/python3.11/site-packages/wd_fw_update/main.py", line 481, in wd_fw_update
    relative_urls = get_fw_url(model=model)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.B5xaB9c0ui/lib/python3.11/site-packages/wd_fw_update/main.py", line 169, in get_fw_url
    raise RuntimeError("No Firmware found for this model. Please check your selection / model.")
RuntimeError: No Firmware found for this model. Please check your selection / model.
```

It seems SN740 isn't in the [usual list](https://wddashboarddownloads.wdc.com/wdDashboard/config/devices/lista_devices.xml) at all, I'm not sure where to find firmware files for this drive.

**Comment by not-a-feature** [comment]
Yes the 740 firmware isn't supported. 
I haven't figured out if/where there is version that could be integrated.

For windows, dell provides an updater: https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=d5c6n&lwp=rt

**Comment by shelvacu** [comment]
https://community.frame.work/t/notes-from-attempting-to-extract-wd-pc-sn740-firmware-from-dell-updater-exe/58376

**Comment by shelvacu** [comment]
I was able to install fw version `731120WD` (labeled as for SN770) and it seems to be working just fine

**Comment by not-a-feature** [comment]
Thanks for diving into this.

According to a few sources the SN 740 is an OEM version of the SN 770.
- https://www.hardwareluxx.de/community/threads/ssd-performance-neue-pcie-4-0-ist-schlechter-als-pcie-3-0.1323859 (German)
- https://community.frame.work/t/m-2-2230-ssd-recommendations-for-the-framework-16/36279/22

While the NAND Flashs have different part numbers, the SN 770 and the SN 740 share at least the same controller.
- https://www.techpowerup.com/ssd-specs/western-digital-sn770m-2-tb.d1673
- https://www.techpowerup.com/ssd-specs/western-digital-sn740-2-tb.d1393

While it seems to work in your case, I'm not confident to include these findings into the updater.

**Comment by shelvacu** [comment]
I totally agree you shouldn't install the firmware automatically; Could you include a link to more information when this model is detected so the user can make their own choice?

**Comment by not-a-feature** [comment]
Sounds good. If i have some spare time i'll implement that

**Comment by auron2k** [comment]
I'm looking to update my SN740 in this way - any issues encountered since doing it? I'm not sure if there's a fairly easy way for me to put this firmware on.

**Comment by shelvacu** [comment]
> any issues encountered since doing it?

Nope! And this reply written from that same laptop with the updated drive

**Comment by josecm65** [comment]
I have a SN740 1tb and use the 731120WD firmware and it works perfectly 

https://i.postimg.cc/1RqS2kzy/Screenshot-2025-10-15-114550.png

**Comment by Arondight** [comment]
also wd SN520 is not support
